### PR TITLE
Fix compilation error when not using Azure support

### PR DESCRIPTION
**Pull request by Xanewok**
This also fixes CI errors. Introduced in #1024.

r? @sylvestre

### CODE REVIEW

**Comment by sylvestre** [comment]
thanks!
