### PR TITLE
Vendor my fork of lru-cache. Fixes #152

### LINKED ISSUE #152: Released version does not compile on Rust 1.18.0
Running `cargo +stable install sccache` => `Installing sccache v0.1.0`

```
error[E0369]: binary operation `==` cannot be applied to type `protobuf::error::WireError`
   --> /Users/shep/.cargo/registry/src/github.com-1ecc6299db9ec823/sccache-0.1.0/src/server.rs:849:24
    |
849 |                     if s == "truncated message" {
    |                        ^
    |
    = note: an implementation of `std::cmp::PartialEq` might be missing for `protobuf::error::WireError`

error[E0277]: the trait bound `protobuf::error::WireError: std::error::Error` is not satisfied
   --> /Users/shep/.cargo/registry/src/github.com-1ecc6299db9ec823/sccache-0.1.0/src/server.rs:852:29
    |
852 |                         Err(io::Error::new(ErrorKind::Other, s))
    |                             ^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `protobuf::error::WireError`
    |
    = note: required because of the requirements on the impl of `std::convert::From<protobuf::error::WireError>` for `std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>`
    = note: required because of the requirements on the impl of `std::convert::Into<std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>>` for `protobuf::error::WireError`
    = note: required by `std::io::Error::new`

error[E0277]: the trait bound `protobuf::error::WireError: std::error::Error` is not satisfied
   --> /Users/shep/.cargo/registry/src/github.com-1ecc6299db9ec823/sccache-0.1.0/src/server.rs:913:52
    |
913 |                 ProtobufError::WireError(s) => Err(io::Error::new(ErrorKind::Other, s)),
    |                                                    ^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `protobuf::error::WireError`
    |
    = note: required because of the requirements on the impl of `std::convert::From<protobuf::error::WireError>` for `std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>`
    = note: required because of the requirements on the impl of `std::convert::Into<std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>>` for `protobuf::error::WireError`
    = note: required by `std::io::Error::new`
```

### PR DESCRIPTION
**Pull request by luser**
I just vendored the lru-cache lib.rs into lru-disk-cache and tweaked a few things to match. This should let us publish on crates.io again.

### CODE REVIEW

**Comment by luser** [comment]
The AppVeyor failures are infra related, something about SSL failing. The Travis Nightly tests failed, but only because the `lru-cache` doctests failed to compile. The Travis config is using `cargo test --all` only on Nightly currently, so it doesn't show up elsewhere.

**Comment by alexcrichton** [comment]
More info about the AppVeyor failure can be [found here](http://help.appveyor.com/discussions/problems/7115-curl-cant-download-files-through-ssl#comment_43044339)
