### ISSUE TITLE
Released version does not compile on Rust 1.18.0

### ISSUE THREAD

**Issue by shepmaster** [mozilla/sccache#152]
Running `cargo +stable install sccache` => `Installing sccache v0.1.0`

```
error[E0369]: binary operation `==` cannot be applied to type `protobuf::error::WireError`
   --> /Users/shep/.cargo/registry/src/github.com-1ecc6299db9ec823/sccache-0.1.0/src/server.rs:849:24
    |
849 |                     if s == "truncated message" {
    |                        ^
    |
    = note: an implementation of `std::cmp::PartialEq` might be missing for `protobuf::error::WireError`

error[E0277]: the trait bound `protobuf::error::WireError: std::error::Error` is not satisfied
   --> /Users/shep/.cargo/registry/src/github.com-1ecc6299db9ec823/sccache-0.1.0/src/server.rs:852:29
    |
852 |                         Err(io::Error::new(ErrorKind::Other, s))
    |                             ^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `protobuf::error::WireError`
    |
    = note: required because of the requirements on the impl of `std::convert::From<protobuf::error::WireError>` for `std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>`
    = note: required because of the requirements on the impl of `std::convert::Into<std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>>` for `protobuf::error::WireError`
    = note: required by `std::io::Error::new`

error[E0277]: the trait bound `protobuf::error::WireError: std::error::Error` is not satisfied
   --> /Users/shep/.cargo/registry/src/github.com-1ecc6299db9ec823/sccache-0.1.0/src/server.rs:913:52
    |
913 |                 ProtobufError::WireError(s) => Err(io::Error::new(ErrorKind::Other, s)),
    |                                                    ^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `protobuf::error::WireError`
    |
    = note: required because of the requirements on the impl of `std::convert::From<protobuf::error::WireError>` for `std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>`
    = note: required because of the requirements on the impl of `std::convert::Into<std::boxed::Box<std::error::Error + std::marker::Sync + std::marker::Send + 'static>>` for `protobuf::error::WireError`
    = note: required by `std::io::Error::new`
```

**Comment by alexcrichton** [comment]
Ah I believe this is just because a new version hasn't been published yet, I finally got around to [removing tokio-serde-bincode](https://github.com/mozilla/sccache/commit/da8fbdb3b53ff32c47f697d86b322a30b58586ac) as a git dependency so I think the only one left is [lru-cache](https://github.com/mozilla/sccache/blob/da8fbdb3b53ff32c47f697d86b322a30b58586ac/lru-disk-cache/Cargo.toml#L9), @luser want to publish that on crates.io so `sccache` itself can be published?

**Comment by rillian** [comment]
[Upstream lru-cache](https://github.com/contain-rs/lru-cache) hasn't responded to PRs lately. I'll ping, but we may need to fork on crates.io.
