### ISSUE TITLE
Build failure on macOS with rustc 1.25.0

### ISSUE THREAD

**Issue by andreastt** [mozilla/sccache#233]
sccache fails to build with rustc 1.25.0 or newer on macOS:

```
   Compiling app_dirs v1.1.1
error[E0282]: type annotations needed
  --> /Users/ato/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^ cannot infer type for `T`

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0282"
error: Could not compile `app_dirs`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sccache v0.2.6`, intermediate artifacts can be found at `/var/folders/3z/3yj7t8sx7_55xscc7v57h6p40000gn/T/cargo-install.WphO2iS8aUK8`

Caused by:
  build failed
```

This is reported to the app_dirs dependency in https://github.com/AndyBarron/app-dirs-rs/issues/28 and was caused by https://github.com/rust-lang/rust/pull/46985. According to the rustc issue https://github.com/rust-lang/rust/issues/48716 this will not be reverted, and a patch to app_dirs is necessary. One exists, but appears to have stalled, in https://github.com/AndyBarron/app-dirs-rs/pull/29.

**Comment by luser** [comment]
Wouldn't you know, I disabled CI coverage of Mac with nightly Rust a while ago (because Travis Mac jobs take forever to run). I'm not sure I would have noticed this anyway given that I have nightly CI set to allow failures.

If the app_dirs fix lands and gets released I will absolutely merge a PR to update to the fixed version.

**Comment by luser** [comment]
I fixed this by removing `app_dirs` and switching to the `directories` crate.

**Comment by luser** [comment]
This broke the mac Rust 1.21 build:
https://travis-ci.org/mozilla/sccache/jobs/356333681

Apparently directories is using the `Try` implementation on `Option`, which first appeared in 1.22.

**Comment by luser** [comment]
I bumped the minimum supported Rust version to 1.22:
https://github.com/mozilla/sccache/commit/ae9517af284ad9ea6ea4fb6c2ffe55f49effce9e
