### ISSUE TITLE
Release 0.2.13 didn't publish windows binaries

### ISSUE THREAD

**Issue by ry** [mozilla/sccache#677]
https://github.com/mozilla/sccache/releases/tag/0.2.13

**Comment by luser** [comment]
Windows CI seems broken in general:
https://ci.appveyor.com/project/luser/sccache2

[The latest build](https://ci.appveyor.com/project/luser/sccache2/build/job/o91asau7v8q9310l) shows these errors:
```
error[E0433]: failed to resolve: use of undeclared type or module `TempDir`
    --> src\compiler\rust.rs:1814:19
     |
1814 |     let tempdir = TempDir::new("sccache_test").unwrap();
     |                   ^^^^^^^ use of undeclared type or module `TempDir`
warning: unused import: `which::which`
  --> src\compiler\c.rs:39:5
   |
39 | use which::which;
   |     ^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
warning: use of deprecated item 'tokio_reactor::Handle::current': semantics were sometimes surprising, use Handle::default()
   --> src\commands.rs:169:37
    |
169 |         NamedPipe::new(&pipe_name, &Handle::current())
    |                                     ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
    --> src\compiler\rust.rs:1824:18
     |
1824 |       let () = ror.handle_outputs(&pt, &[depinfo_file.clone()]).unwrap();
     |                    ^^^^^^^^^^^^^^ expected 3 parameters
     | 
    ::: src\compiler\compiler.rs:640:5
     |
640  | /     fn handle_outputs(
641  | |         self: Box<Self>,
642  | |         path_transformer: &dist::PathTransformer,
643  | |         output_paths: &[PathBuf],
644  | |         extra_inputs: &[PathBuf],
645  | |     ) -> Result<()>;
     | |____________________- defined here
warning: unused import: `OsStrExt`
  --> src\compiler\msvc.rs:22:37
   |
22 | use crate::util::{run_input_output, OsStrExt};
   |                                     ^^^^^^^^
error: aborting due to 2 previous errors
Some errors have detailed explanations: E0061, E0433.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `sccache`.
```

[The build on the 0.2.13 tag](https://ci.appveyor.com/project/luser/sccache2/builds/31024661) has similar errors.

**Comment by ry** [comment]
I can potentially contribute some CI changes to get it running on Github Actions. We've had a good experience [in Deno](https://github.com/denoland/deno/blob/master/.github/workflows/ci.yml) doing cross platform builds with GHA.

**Comment by luser** [comment]
That's up to @chmanchester  and @froydnj who are actively maintaining the project now. The Windows builds seem to be actually broken, fixing that ought to fix this issue.

**Comment by froydnj** [comment]
#678 fixed a bunch of problems at the cost of having to increase some timeouts and disable some tests, so Windows is green again.  @ry if you wanted to contribute Actions, that'd be great!

**Comment by froydnj** [comment]
Just to follow up here, @ry contributed Actions, but unfortunately we can't enable them for the repository: Mozilla's Github account is considered a "legacy" account and doesn't have access to things like Actions...and upgrading Mozilla's account isn't likely to happen for a variety of factors. :(

I'll try to pay attention to the state of the Windows CI and fix problems as they come.

**Comment by ry** [comment]
@froydnj Oh bummer. Ok we might as well remove the dead code then: https://github.com/mozilla/sccache/pull/703

**Comment by glandium** [comment]
Note the github page about actions says "GitHub Actions is not available for private repositories owned by accounts using legacy per-repository plans". This is not a private repository.

**Comment by menaquinoneK2** [comment]
no sccache for me then
```
 0:07.86 checking for ccache... C:/sccache-0.2.12-x86_64-pc-windows-msvc/sccache
.exe
 0:07.93 ERROR: sccache 0.2.13 or later is required. sccache in use at C:/sccach
e-0.2.12-x86_64-pc-windows-msvc/sccache.exe has
 0:07.93 version 0.2.12.
 0:07.93 Please upgrade or acquire a new version with |./mach bootstrap|.
 0:08.10 *** Fix above errors and then restart with\
 0:08.10                "./mach build"
 0:08.12 mozmake.EXE: *** [client.mk;115: configure] Error 1
```
Maybe it should tell me how ` |./mach bootstrap|` will acquire it, like what args do I need to give it to do so...

oh, wait a second I think I found something: `C:\Users\John\.mozbuild\sccache\sccache.exe` is `sccache 0.2.14-alpha.0` ergo, just `./mach bootstrap` did acquire it automagically, I just didn't know it did, and thus I can now use `mozconfig` setting `ac_add_options --with-ccache=C:/Users/John/.mozbuild/sccache/sccache.exe` (confirmed, passes initial muster)

**Comment by filips123** [comment]
Any update? AppVeyor builds seem to be passing again, but no artifact is published because there isn't any new release. Would creating another release help?

**Comment by glandium** [comment]
0.2.14 was released and has binaries that were built on appveyor. For some reason, the upload didn't go through, so I had to download the artifacts from there manually and add them to the release. Since we're going to be moving off Travis-CI shortly, we'll bring all platforms to the same workflow (most probably Github actions), and all release artifacts should work equally well.

**Comment by luser** [comment]
[The Appveyor build](https://ci.appveyor.com/project/luser/sccache2/builds/36952454) shows an error:

```
Deploying using GitHub provider
Creating "0.2.14" release for repository "mozilla/sccache" tag "0.2.14" commit "655ef1a69691be4fcdcb8990dfca1001df5af129"...Error creating GitHub release: Error reading repository 'mozilla/sccache' releases: 401 - Unauthorized
```

Not sure what happened there, but if you're switching to GitHub Actions it's not really worth investigating.
